### PR TITLE
express added ready for deploy to heroku

### LINKED ISSUE #14: Deploy to Heroku
Setup project for deployment

### PR DESCRIPTION
**Pull request by rachelthecodesmith**
Added express, checked all tests still passing and can run on local port 8080 with full functionality. Profile added, ready for deploy to heroku.

Squirrel us.

Closes #14 
#14

### CODE REVIEW

**Comment by mic-css** [comment]
Deploy to heroku first OR NO SQUIRREL FOR YOU YOUNG LADIES

**Comment by rachelthecodesmith** [comment]
add issue - Mic's caps lock is broken

add issue - less of the patronising young ladies language plz!

**Comment by esbaddeley** [comment]
Up and running on Heroku! 

We needed to dynamically declare the port the app will be listening on in the server.js file. 

https://octosearchleo.herokuapp.com/

**Comment by arnoldmanzano** [comment]
:shipit:

**Pull request merged**
