### PR TITLE
10 create readme

### LINKED ISSUE #10: Create README

### PR DESCRIPTION
**Pull request by esbaddeley**
Hi Guys,

Can you check through the updated README and let us know any suggestions for amendments/additions

Then squirrel it!

Closes #10

### CODE REVIEW

**Comment by arnoldmanzano** [comment]
Readme and screenshots looks good, well explained and good detail.

Waffle seems to have created a new ticket/issue number because the PR didn't contain the closes #n tag. Can that be adjusted before merging, just for waffle cleanup purposes?

**Comment by mic-css** [comment]
I edited Emma's comment to close #10, not sure if that'll do it

**Comment by mic-css** [comment]
Please check updated README

**Comment by arnoldmanzano** [comment]
:shipit:

**Pull request merged**
