### PR TITLE
1 displaying users

### LINKED ISSUE #1: list Github users [user story]
As a hiring partner
So I can view information about Github users rapidly
I want a list of Github users

### PR DESCRIPTION
**Pull request by esbaddeley**
Finished user story one with a placeholder http request function in the controller.

Closes #1

### CODE REVIEW

**Comment by mic-css** [comment]
AAAHH SO YOU WANT A SQUIRREL

**Comment by mic-css** [comment]
All tests passing :smiley:

**Comment by mic-css** [comment]
All tests passing :smiley:

**Comment by esbaddeley** [comment]
Really have fixed the tests this time!

**Comment by mic-css** [comment]
:shipit:

**Pull request merged**
