### PR TITLE
8 animations

### LINKED ISSUE #8: animations on search submission and content load [user story] [nice to have]

### PR DESCRIPTION
**Pull request by arnoldmanzano**
Added ng-animate, and css animations.
Adjusted classes for animation support.
Some css tweaks.

Closes #8

### CODE REVIEW

**Comment by arnoldmanzano** [comment]
Along with the code to be reviewed, would like your feedback if the animation looks good. :smile:

**Comment by mic-css** [comment]
slick :shipit:

**Comment by esbaddeley** [comment]
Looking great! :shipit:

**Comment by arnoldmanzano** [comment]
Merged latest dev to fix all the conflicts.

**Comment by mic-css** [comment]
:shipit:

**Pull request merged**
